-----------------FACT_TESTING-----------------------------

CREATE TABLE FACT_ORDER_LINE_CHRG_sql_IN1542(

SALES_ORDER_NUM	bigint  not null,
SALES_ORDER_LINE_NUM	INT not null,
TENANT_ORG_ID	INT not null,
CHARGE_CATEG_ID	INT not null,
CHRG_CATEG_MAP_ID	INT not null,
CHARGE_NM	VARCHAR(50) not null,
CHARGE_AMT	DECIMAL(19,6) not null,
CHRG_CRE_DT	DATETIME not null,
CHRG_QTY	INT not null,
CHRG_CRE_DT_KEY	INT not null,
charge_categ_key	INT not null);

drop table FACT_ORDER_LINE_CHRG_IN1542
DIM_CHARGE_CATEG_SQL_IN1542
 dim_day_sql_in1542

 insert into FACT_ORDER_LINE_CHRG_sql_IN1542 
 select 

 IIF(o.SALES_ORDER_NUM    IS NULL OR   o.SALES_ORDER_NUM='null',101,convert(bigint,LTRIM(RTRIM(o.SALES_ORDER_NUM))))as SALES_ORDER_NUM
,IIF(o.SALES_ORDER_LINE_NUM    IS NULL OR   o.SALES_ORDER_LINE_NUM='null',101,CONVERT(INT,ltrim(rtrim(o.SALES_ORDER_LINE_NUM))))as SALES_ORDER_LINE_NUM
,IIF(o.TENANT_ORG_ID    IS NULL OR   o.TENANT_ORG_ID='null',101,CONVERT(INT,LTRIM(RTRIM(o.TENANT_ORG_ID))))as TENANT_ORG_ID
,IIF(o.CHARGE_CATEG_ID    IS NULL OR   o.CHARGE_CATEG_ID='null',101,CONVERT(INT,LTRIM(RTRIM(o.CHARGE_CATEG_ID))))as CHARGE_CATEG_ID
,IIF(o.CHRG_CATEG_MAP_ID    IS NULL OR   o.CHRG_CATEG_MAP_ID='null',101,CONVERT(INT,LTRIM(RTRIM(o.CHRG_CATEG_MAP_ID))))as CHRG_CATEG_MAP_ID
,IIF(O.CHARGE_NM    IS NULL OR   O.CHARGE_NM='null','N/A' ,LTRIM(RTRIM(O.CHARGE_NM)))as CHARGE_NM
,IIF(O.CHARGE_AMT    IS NULL OR   O.CHARGE_AMT='null',101 ,CONVERT(DECIMAL(19,6),LTRIM(RTRIM(O.CHaRGe_AMT))))as CHARGE_AMT
,IIF(O.CHRG_CRE_DT    IS NULL OR   O.CHRG_CRE_DT='null','01-01-1900',CONVERT(DATETIME,LTRIM(RTRIM(O.CHRG_CRE_DT))))as CHRG_CRE_DT
,IIF(O.CHRG_QTY    IS NULL OR   O.CHRG_QTY='null',101,CONVERT(INT,LTRIM(RTRIM(O.CHRG_QTY))))as CHRG_QTY
,D.DAY_KEY AS CHRG_CRE_DT_KEY 
,C.charge_categ_key AS charge_categ_key
from [BCMPWMT].[ORDER_LINE_CHRG] o left join  dim_day_sql_in1542 d
on iif(o.CHRG_CRE_DT is null or  o.CHRG_CRE_DT is not null ,'01-01-1990',format(convert(datetime,o.CHRG_CRE_DT),'yyyy-MM-dd'))=d.date_id
left join DIM_CHARGE_CATEG_SQL_IN1542 c
on C.CHARGE_CATEG_ID=IIF(O.CHARGE_CATEG_ID IS NULL OR O.CHARGE_CATEG_ID ='NULL',101 ,CONVERT(INT,LTRIM(RTRIM(O.CHARGE_CATEG_ID))))

-----------ROW COUNT-------------
SELECT COUNT(*) FROM FACT_ORDER_LINE_CHRG_sql_IN1542 
SELECT COUNT(*) FROM (
 select 

 IIF(o.SALES_ORDER_NUM    IS NULL OR   o.SALES_ORDER_NUM='null',101,convert(bigint,LTRIM(RTRIM(o.SALES_ORDER_NUM))))as SALES_ORDER_NUM
,IIF(o.SALES_ORDER_LINE_NUM    IS NULL OR   o.SALES_ORDER_LINE_NUM='null',101,CONVERT(INT,ltrim(rtrim(o.SALES_ORDER_LINE_NUM))))as SALES_ORDER_LINE_NUM
,IIF(o.TENANT_ORG_ID    IS NULL OR   o.TENANT_ORG_ID='null',101,CONVERT(INT,LTRIM(RTRIM(o.TENANT_ORG_ID))))as TENANT_ORG_ID
,IIF(o.CHARGE_CATEG_ID    IS NULL OR   o.CHARGE_CATEG_ID='null',101,CONVERT(INT,LTRIM(RTRIM(o.CHARGE_CATEG_ID))))as CHARGE_CATEG_ID
,IIF(o.CHRG_CATEG_MAP_ID    IS NULL OR   o.CHRG_CATEG_MAP_ID='null',101,CONVERT(INT,LTRIM(RTRIM(o.CHRG_CATEG_MAP_ID))))as CHRG_CATEG_MAP_ID
,IIF(O.CHARGE_NM    IS NULL OR   O.CHARGE_NM='null','N/A' ,LTRIM(RTRIM(O.CHARGE_NM)))as CHARGE_NM
,IIF(O.CHARGE_AMT    IS NULL OR   O.CHARGE_AMT='null',101 ,CONVERT(DECIMAL(19,6),LTRIM(RTRIM(O.CHaRGe_AMT))))as CHARGE_AMT
,IIF(O.CHRG_CRE_DT    IS NULL OR   O.CHRG_CRE_DT='null','01-01-1900',CONVERT(DATETIME,LTRIM(RTRIM(O.CHRG_CRE_DT))))as CHRG_CRE_DT
,IIF(O.CHRG_QTY    IS NULL OR   O.CHRG_QTY='null',101,CONVERT(INT,LTRIM(RTRIM(O.CHRG_QTY))))as CHRG_QTY
,D.DAY_KEY AS CHRG_CRE_DT_KEY 
,C.charge_categ_key AS charge_categ_key
from [BCMPWMT].[ORDER_LINE_CHRG] o left join  dim_day_sql_in1542 d
on iif(o.CHRG_CRE_DT is null or  o.CHRG_CRE_DT is not null ,'01-01-1990',format(convert(datetime,o.CHRG_CRE_DT),'yyyy-MM-dd'))=d.date_id
left join DIM_CHARGE_CATEG_SQL_IN1542 c
on C.CHARGE_CATEG_ID=IIF(O.CHARGE_CATEG_ID IS NULL OR O.CHARGE_CATEG_ID ='NULL',101 ,CONVERT(INT,LTRIM(RTRIM(O.CHARGE_CATEG_ID)))))S

----------------ROW COUNT GROUP BY---------------------
SELECT * FROM FACT_ORDER_LINE_CHRG_sql_IN1542 
SELECT CHARGE_CATEG_ID, COUNT(*) COUNTA FROM FACT_ORDER_LINE_CHRG_IN1542 GROUP BY CHARGE_CATEG_ID
SELECT CHARGE_CATEG_ID,COUNT(*) FROM (
 select 

 IIF(o.SALES_ORDER_NUM    IS NULL OR   o.SALES_ORDER_NUM='null',101,convert(bigint,LTRIM(RTRIM(o.SALES_ORDER_NUM))))as SALES_ORDER_NUM
,IIF(o.SALES_ORDER_LINE_NUM    IS NULL OR   o.SALES_ORDER_LINE_NUM='null',101,CONVERT(INT,ltrim(rtrim(o.SALES_ORDER_LINE_NUM))))as SALES_ORDER_LINE_NUM
,IIF(o.TENANT_ORG_ID    IS NULL OR   o.TENANT_ORG_ID='null',101,CONVERT(INT,LTRIM(RTRIM(o.TENANT_ORG_ID))))as TENANT_ORG_ID
,IIF(o.CHARGE_CATEG_ID    IS NULL OR   o.CHARGE_CATEG_ID='null',101,CONVERT(INT,LTRIM(RTRIM(o.CHARGE_CATEG_ID))))as CHARGE_CATEG_ID
,IIF(o.CHRG_CATEG_MAP_ID    IS NULL OR   o.CHRG_CATEG_MAP_ID='null',101,CONVERT(INT,LTRIM(RTRIM(o.CHRG_CATEG_MAP_ID))))as CHRG_CATEG_MAP_ID
,IIF(O.CHARGE_NM    IS NULL OR   O.CHARGE_NM='null','N/A' ,LTRIM(RTRIM(O.CHARGE_NM)))as CHARGE_NM
,IIF(O.CHARGE_AMT    IS NULL OR   O.CHARGE_AMT='null',101 ,CONVERT(DECIMAL(19,6),LTRIM(RTRIM(O.CHaRGe_AMT))))as CHARGE_AMT
,IIF(O.CHRG_CRE_DT    IS NULL OR   O.CHRG_CRE_DT='null','01-01-1900',CONVERT(DATETIME,LTRIM(RTRIM(O.CHRG_CRE_DT))))as CHRG_CRE_DT
,IIF(O.CHRG_QTY    IS NULL OR   O.CHRG_QTY='null',101,CONVERT(INT,LTRIM(RTRIM(O.CHRG_QTY))))as CHRG_QTY
,D.DAY_KEY AS DCHRG_CRE_DT_KEY 
,C.charge_categ_key AS charge_categ_key
from [BCMPWMT].[ORDER_LINE_CHRG] o left join  dim_day_sql_in1542 d
on iif(o.CHRG_CRE_DT is null or  o.CHRG_CRE_DT is not null ,'01-01-1990',format(convert(datetime,o.CHRG_CRE_DT),'yyyy-MM-dd'))=d.date_id
left join DIM_CHARGE_CATEG_SQL_IN1542 c
on C.CHARGE_CATEG_ID=IIF(O.CHARGE_CATEG_ID IS NULL OR O.CHARGE_CATEG_ID ='NULL',101 ,CONVERT(INT,LTRIM(RTRIM(O.CHARGE_CATEG_ID)))))S GROUP BY CHARGE_CATEG_ID
---------------------------REFERENCE INTEGRITY CHECK-----------------
select count(SO.CHRG_CRE_DT_KEY),
count(SO.charge_categ_key)
FROM FACT_ORDER_LINE_CHRG_sql_IN1542 SO 
LEFT JOIN 
 
 dim_day_sql_in1542 d ON D.DAY_KEY =SO.CHRG_CRE_DT_KEY 
 LEFT JOIN  DIM_CHARGE_CATEG_SQL_IN1542 c ON
 C.charge_categ_key=SO.charge_categ_key

 WHERE d.date_id IS NULL AND
 C.CHARGE_CATEG_ID IS NULL

----------------------STARTIFICATION CHECK----------------
SELECT * FROM FACT_ORDER_LINE_CHRG_sql_IN1542 

SELECT SUM(CHARGE_AMT)CHARGE_AMT , SUM(IIF(CHRG_QTY=101,0 ,CHRG_QTY))CHRG_QTY FROM FACT_ORDER_LINE_CHRG_IN1542

SELECT SUM(CHARGE_AMT)CHARGE_AMT, SUM(IIF(CHRG_QTY=101,0 ,CHRG_QTY))CHRG_QTY  FROM (
 select 

 IIF(o.SALES_ORDER_NUM    IS NULL OR   o.SALES_ORDER_NUM='null',101,convert(bigint,LTRIM(RTRIM(o.SALES_ORDER_NUM))))as SALES_ORDER_NUM
,IIF(o.SALES_ORDER_LINE_NUM    IS NULL OR   o.SALES_ORDER_LINE_NUM='null',101,CONVERT(INT,ltrim(rtrim(o.SALES_ORDER_LINE_NUM))))as SALES_ORDER_LINE_NUM
,IIF(o.TENANT_ORG_ID    IS NULL OR   o.TENANT_ORG_ID='null',101,CONVERT(INT,LTRIM(RTRIM(o.TENANT_ORG_ID))))as TENANT_ORG_ID
,IIF(o.CHARGE_CATEG_ID    IS NULL OR   o.CHARGE_CATEG_ID='null',101,CONVERT(INT,LTRIM(RTRIM(o.CHARGE_CATEG_ID))))as CHARGE_CATEG_ID
,IIF(o.CHRG_CATEG_MAP_ID    IS NULL OR   o.CHRG_CATEG_MAP_ID='null',101,CONVERT(INT,LTRIM(RTRIM(o.CHRG_CATEG_MAP_ID))))as CHRG_CATEG_MAP_ID
,IIF(O.CHARGE_NM    IS NULL OR   O.CHARGE_NM='null','N/A' ,LTRIM(RTRIM(O.CHARGE_NM)))as CHARGE_NM
,IIF(O.CHARGE_AMT    IS NULL OR   O.CHARGE_AMT='null',101 ,CONVERT(DECIMAL(19,6),LTRIM(RTRIM(O.CHaRGe_AMT))))as CHARGE_AMT
,IIF(O.CHRG_CRE_DT    IS NULL OR   O.CHRG_CRE_DT='null','01-01-1900',CONVERT(DATETIME,LTRIM(RTRIM(O.CHRG_CRE_DT))))as CHRG_CRE_DT
,IIF(O.CHRG_QTY    IS NULL OR   O.CHRG_QTY='null',101,CONVERT(INT,LTRIM(RTRIM(O.CHRG_QTY))))as CHRG_QTY
,D.DAY_KEY AS DCHRG_CRE_DT_KEY 
,C.charge_categ_key AS charge_categ_key
from [BCMPWMT].[ORDER_LINE_CHRG] o left join  dim_day_sql_in1542 d
on iif(o.CHRG_CRE_DT is null or  o.CHRG_CRE_DT is not null ,'01-01-1990',format(convert(datetime,o.CHRG_CRE_DT),'yyyy-MM-dd'))=d.date_id
left join DIM_CHARGE_CATEG_SQL_IN1542 c
on C.CHARGE_CATEG_ID=IIF(O.CHARGE_CATEG_ID IS NULL OR O.CHARGE_CATEG_ID ='NULL',101 ,CONVERT(INT,LTRIM(RTRIM(O.CHARGE_CATEG_ID)))))S
-----------------STARTIFICATION CHECK GROUP BY ---------------
SELECT SUM(CHARGE_AMT) AS CHARGE_AMT , SUM(IIF(CHRG_QTY=101,0 ,CHRG_QTY))CHRG_QTY FROM FACT_ORDER_LINE_CHRG_IN1542 GROUP BY CHARGE_NM ,  CHRG_CRE_DT_KEY

SELECT SUM(CHARGE_AMT)CHARGE_AMT, SUM(IIF(CHRG_QTY=101,0 ,CHRG_QTY))CHRG_QTY FROM (
 select 

 IIF(o.SALES_ORDER_NUM    IS NULL OR   o.SALES_ORDER_NUM='null',101,convert(bigint,LTRIM(RTRIM(o.SALES_ORDER_NUM))))as SALES_ORDER_NUM
,IIF(o.SALES_ORDER_LINE_NUM    IS NULL OR   o.SALES_ORDER_LINE_NUM='null',101,CONVERT(INT,ltrim(rtrim(o.SALES_ORDER_LINE_NUM))))as SALES_ORDER_LINE_NUM
,IIF(o.TENANT_ORG_ID    IS NULL OR   o.TENANT_ORG_ID='null',101,CONVERT(INT,LTRIM(RTRIM(o.TENANT_ORG_ID))))as TENANT_ORG_ID
,IIF(o.CHARGE_CATEG_ID    IS NULL OR   o.CHARGE_CATEG_ID='null',101,CONVERT(INT,LTRIM(RTRIM(o.CHARGE_CATEG_ID))))as CHARGE_CATEG_ID
,IIF(o.CHRG_CATEG_MAP_ID    IS NULL OR   o.CHRG_CATEG_MAP_ID='null',101,CONVERT(INT,LTRIM(RTRIM(o.CHRG_CATEG_MAP_ID))))as CHRG_CATEG_MAP_ID
,IIF(O.CHARGE_NM    IS NULL OR   O.CHARGE_NM='null','N/A' ,LTRIM(RTRIM(O.CHARGE_NM)))as CHARGE_NM
,IIF(O.CHARGE_AMT    IS NULL OR   O.CHARGE_AMT='null',0 ,CONVERT(DECIMAL(19,6),LTRIM(RTRIM(O.CHaRGe_AMT))))as CHARGE_AMT
,IIF(O.CHRG_CRE_DT    IS NULL OR   O.CHRG_CRE_DT='null','01-01-1900',CONVERT(DATETIME,LTRIM(RTRIM(O.CHRG_CRE_DT))))as CHRG_CRE_DT
,IIF(O.CHRG_QTY    IS NULL OR   O.CHRG_QTY='null',0,CONVERT(INT,LTRIM(RTRIM(O.CHRG_QTY))))as CHRG_QTY
,D.DAY_KEY AS DCHRG_CRE_DT_KEY 
,C.charge_categ_key AS charge_categ_key
from [BCMPWMT].[ORDER_LINE_CHRG] o left join  dim_day_sql_in1542 d
on iif(o.CHRG_CRE_DT is null or  o.CHRG_CRE_DT is not null ,'01-01-1990',format(convert(datetime,o.CHRG_CRE_DT),'yyyy-MM-dd'))=d.date_id
left join DIM_CHARGE_CATEG_SQL_IN1542 c
on C.CHARGE_CATEG_ID=IIF(O.CHARGE_CATEG_ID IS NULL OR O.CHARGE_CATEG_ID ='NULL',101 ,CONVERT(INT,LTRIM(RTRIM(O.CHARGE_CATEG_ID)))))S GROUP BY CHARGE_NM,dCHRG_CRE_DT_KEY
----------------------------------------------
